### PR TITLE
Fix build with newer FFmpeg, sync up with latest upstream

### PR DESCRIPTION
**Pull request by dougg3**
CODEC_FLAG_TRUNC and CODEC_CAP_TRUNC were removed from newer versions of FFmpeg. This fixes the build on Fedora 38 for example.

I also noticed that GitHub Actions no longer supports Ubuntu 18.04 so I removed that config.

Finally, I synced up with the upstream version, which seems to just be tweaks to the version number.

### CODE REVIEW

**Comment by dougg3** [comment]
This should fix #20

**Comment by dikkedimi** [comment]
Currently trying to build on Kubuntu 24.04, because the last release does not seem to show up in OBS.

I'm not sure if this is related although it seems to be.

```

98% building CXX object CMakeFiles/obs-ios-camera-source.dir/src/FFMpegVideoDecoder.cpp.o
/home/user/Downloads/obs-ios-camera-source/src/ffmpeg-decode.c:19:10: fatal error: obs-ffmpeg-compat.h: No such file or directory
   19 | #include "obs-ffmpeg-compat.h"
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/obs-ios-camera-source.dir/build.make:104: CMakeFiles/obs-ios-camera-source.dir/src/ffmpeg-decode.c.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:112: CMakeFiles/obs-ios-camera-source.dir/all] Error 2

make: *** [Makefile:136: all] Error 2

```

**Comment by dougg3** [comment]
Hi @dikkedimi, I am seeing the same problem in Ubuntu MATE 24.04. I'll see if I can figure out what's wrong. I'm guessing something changed in a newer OBS.

**Comment by dougg3** [comment]
Thanks for your report! New builds are available [here](https://github.com/dougg3/obs-ios-camera-source/releases/tag/20240815), and the plugin should now compile successfully for you if you want to install it that way instead.
